tknerr/bills-kitchen

- CHANGELOG.md
- README.md
- Rakefile
- files/home/.bundle/config
- files/home/.gemrc
- files/set-env.bat
- files/set-env.ps1
- spec/helpers.rb
- spec/integration/bills_kitchen_spec.rb
Updates to the latest ChefDK 0.3.6, including:
* chefdk version update to 0.3.6
* remove some unncessary fixes from `#fix_chefdk` method in Rakefile
* mimic `chef shell-init` by setting env vars accordingly
* restoring original behaviour of using `$HOME/.chefdk` for user installed gems (see #71)
* adapt tests where necessary
> Chefdk update

- CHANGELOG.md
- README.md
- Rakefile
- spec/integration/bills_kitchen_spec.rb
This PR simply updates to the latest ChefDK 0.4.0
All integration & acceptance tests pass.
> Update to ChefDK 0.4.0

- CHANGELOG.md
- files/home/.kitchen/config.yml
- files/home/.vagrant.d/Vagrantfile
This is a hack-like workaround to limit caching of the generic busser gems cache to occasions when we are running as part of a test-kitchen run.
We use `Dir.pwd` to guess whether we are in a kitchenci generated directory and thus can assume we are running in a kitchenci run with the kitchen-vagrant plugin.
*Why* doing this? Because
1. we only need it in this case and 
2. it alleviates problems with windows guests (see https://github.com/fgrehm/vagrant-cachier/issues/137)
> Enable caching of busser gems only if we are in a test-kitchen run

- CHANGELOG.md
- README.md
- Rakefile
- spec/integration/bills_kitchen_spec.rb
This PR is here to update the ChefDK to version 0.5.0. 
Currently 0.5.0-rc2 is out. Once the final version is out and everything works ok we can merge it.
> Update to Chefdk 0.5.0

- CHANGELOG.md
- files/home/.vagrant.d/Vagrantfile
Sometimes a vagrant provider is not compatible with vagrant-cachier.
This conflicts with our approach to transparently enable cachier via the global `~/.vagrant.d/Vagrantfile`. 
Since such incompatibiliies are rarely the case under our controlled devpack environment, we keep cachier enabled (sane default), but allow to disable it via the `GLOBAL_VAGRANT_CACHIER_DISABLED` env var:
* if set, cachier will be disabled in the global Vagrantfile (but can still be enabled on a per project basis)
* if unset, cachier will be enabled by default via the global Vagrantfile
Related incompatibility:
https://github.com/fgrehm/vagrant-cachier/issues/142
> Add env var to disable cachier in the global Vagrantfile

- CHANGELOG.md
- files/tools/docker/b2d-start.bat
- files/tools/docker/b2d-stop.bat
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/action/create.rb
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/provider.rb
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/synced_folder.rb
Now that we have the `docker.exe` running locally on Windows, together with boot2docker as the remote `$DOCKER_HOST`, it would make sense to use that as a remote docker host in Vagrant too.
Why?
* it's possible (since the docker 1.6 windows release 3 weeks ago)
* it's faster (no proxying via another mitchellh/boot2docker VM middleman)
* the mitchellh/boot2docker VM is still on docker 1.2, and has not been updated since then
* let's reuse a single docker host and not cache every image twice
As of Vagrant 1.7.2 remote docker host support does not exist yet, but should be trivial to be added:
https://twitter.com/tknerr_de/status/592555809449627648
This PR does the minimal necessary patch to the bill's kitchen vagrant 1.7.2 installation required to make remote docker host support work on …
> Patch Vagrant for Remote Docker Host Support (Experimental)

- CHANGELOG.md
- files/tools/scripts/b2d-start.bat
Fixes the issues reported in #104 
1. [x] check for existence of `BK_ROOT` env var rather than (accidentally) nulling it out
2. [x] make sure the mount point exists before mounting (we were just lucky with /c/ since that already exists by default for the C:/Users mount)
3. [x] make sure it does the right thing and does not fail when the "boot2docker-vm" does not exist initially
> Fix boot2docker start script (b2d-start)

- files/tools/scripts/b2d-start.bat
If it does not exist in `%HOME%\.boot2docker\`, but the "boot2docker-vm" does still exist, it will result in the VM not booting, without an error message. The underlying cause is that the VM has the iso image mounted. And if this points to a non-exisiting file, it will not come up.
This can happen after updating to a new bills kitchen release, where the boot2docker VM remains but the bills ktchen W:\home\.boot2docker dir is wiped.
This PR fixes it by ensuring the iso image always exists when running `b2d-start`
(closely related to #104)
> ensure boot2docker.iso image always exists in `b2d-start`

- CHANGELOG.md
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/synced_folder.rb
nothing more to say... except that with this PR it works now for any drive letter
> fix docker volume mounts, which were working with the C: drive only

- CHANGELOG.md
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/action/host_machine_port_checker.rb
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/provider.rb
Continuation of the earlier work in #100 with the following improvements
* now working with multi-machine setups too
> [WIP] Improve Vagrant Remote Docker Host Support

- CHANGELOG.md
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/action/host_machine_port_checker.rb
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/provider.rb
Makes the experimental Vagrant remote docker host support from #100 work with multi-machine setups, too:
* detects and reports ssh port forwarding conflicts (port collisions) so they can be auto-corrected by Vagrant
* uses the actual forwarded ssh port instead of hardcoding port "2222"
> Fix Vagrant Remote Docker Host Support with Multi-machine Setups

- CHANGELOG.md
- Rakefile
- files/home/.atom/config.cson
- spec/integration/bills_kitchen_spec.rb
Yeah, Atom 1.0 is out :-)
http://blog.atom.io/2015/06/25/atom-1-0.html
This PR updates to atom 1.0:
* removes sublime-tabs which is now part of atom core
* restores line-height 1.2 and sublime-tabs behaviour
> Update to Atom 1.0

- CHANGELOG.md
- Rakefile
- spec/integration/bills_kitchen_spec.rb
update to latest version 1.2.1 of the vagrant-cachier plugin, which supports chef-zero
> Update to vagrant-cachier 1.2.1 with chef-zero support

- CHANGELOG.md
- README.md
- Rakefile
- appveyor.yml
- files/tools/scripts/b2d-start.bat
- spec/integration/bills_kitchen_spec.rb
Updates both:
* docker client to 1.7.1
* boot2docker 1.7.1
Also replaces the `boot2docker download` command in `b2d-start.bat` with a plain `curl` command so that we have explicit control over the boot2docker iso image version that is being downloaded.
You will find some commits inbetween that optimize for running acceptance tests on appveyor (.e.g reducing memory of the boot2docker-vm), but in the end the 40 minutes we have on appveyor does not suffice for running the acceptance tests...
> Update to Docker 1.7.1

- CHANGELOG.md
- README.md
- Rakefile
- files/set-env.bat
- files/set-env.ps1
- spec/integration/bills_kitchen_spec.rb
Chef-DK 0.7.0 is about to come out:
https://github.com/chef/chef-dk/blob/0.7.0.rc.4/CHANGELOG.md#last-release-070
This PR is still work in progress. Currently it:
* updates to 0.7.0-rc4
* sets the new `$CHEFDK_HOME` env var
* adds an initial test for checking `chef env`
> Update to ChefDK 0.7

- CHANGELOG.md
- files/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/docker/provider.rb
This PR fixes two issues when working with the experimental remote docker host support in Vagrant (use `set VAGRANT_DOCKER_REMOTE_HOST_PATCH=1` to enable it):
1. the remote docker host IP was hardcoded to `192.168.59.103`
2. the forwarded ssh host port was always reported as `2222` (the vagrant default for forwarding the ssh port), meaning that it was essentially broken as soon as you started a second VM
This has been fixed by:
1. parsing the remote docker host IP from the `DOCKER_HOST` env var
2. using the actual / real forwarded ssh port that `docker inspect <container>` shows
> Further Fixes in Vagrant Remote Docker Host Support

- CHANGELOG.md
- files/home/.gitconfig
Improve the `.gitconfig`:
* explicitly adopt the new Git 2.0 push behaviour (`push.default = simple`) to get rid of the warning message
* add `git graph` alias to show the commit graph / branches on the commandline without a GUI tool
> Improve git config

- Rakefile
The download URLs from https://dl.bintray.com no longer work anymore.
All hashicorp packages are now served from https://releases.hashicorp.com
> fix URLs for hashicorp downloads

- CHANGELOG.md
- README.md
- Rakefile
- spec/integration/bills_kitchen_spec.rb
This PR updates:
* vagrant 1.8.1
* chefdk  0.13.21
Along the way it removes some workarounds that are not necessary anymore
> Update to Vagrant 1.8 and ChefDK 0.13

- CHANGELOG.md
- Rakefile
This PR adds a differentiaton of the `:clean` vs `:wipe` tasks:
* `rake clean` only cleans the build output directory
* `rake wipe` cleans the whole target directory, including the cache for downloaded files
Also, the method for removing the atom packages with overly long windows paths has been improved to use the windows builtin robocopy tool, instead of trying to uninstall the plugins. So it works more reliably now.
> Differentiate between :clean vs :wipe tasks

- CHANGELOG.md
- Rakefile
- spec/integration/bills_kitchen_spec.rb
Updates to Atom 1.7.3
Seems to work well after a while, only the `~` char can not by typed. Might be related to https://github.com/f/atom-term2/issues/127, but googling around did not reveal a workaround so far. Will merge anyway and fix this later
> Update to latest Atom 1.7.3 Editor

- CHANGELOG.md
- Rakefile
- spec/integration/bills_kitchen_spec.rb
Updates: 
* vagrant-proxyconf to 1.5.2 
* vagrant-berkshelf to 4.1.0
All other vagrant plugins are up to date
> Update Vagrant Plugins
